name: CI

on:
  push:
    branches: [ master, refactor-for-microservices ]
  pull_request:
    branches: [ master, refactor-for-microservices ]

jobs:
  server:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x]
    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_USER: cabbagemeet
          MARIADB_PASSWORD: cabbagemeet
          MARIADB_DATABASE: cabbagemeet
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
        # Adapted from https://stackoverflow.com/a/54854239
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: npm ci
    - name: E2E tests (MariaDB)
      run: npm run test:e2e:mariadb

